[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[colors.primary]
background = "#1e1e2e"

[window]
opacity = 0.9
