theme = "github-dark"
appearance = "system"

diff_view = "unified"
ignore_whitespace = false
show_file_list = true
mouse = true
leader = ";"
comment_vim = true
comment_tab_width = 2
wrap = true
cursor_line = true
transparent_background = true
scroll_offset = 5
no_update_check = false
review_watch_interval_ms = 1000

comment_types = [
  { id = "note", label = "question", definition = "ask for clarification", color = "yellow" },
  { id = "suggestion", definition = "possible improvements" },
  { id = "issue", definition = "problems to fix" },
  { id = "praise", definition = "positive feedback" },
  { id = "nit", label = "nitpick", definition = "small optional tweaks", color = "#d19a66" },
]
