theme = "github-dark"
appearance = "system"

diff_view = "unified"
ignore_whitespace = false
show_file_list = true
mouse = true
leader = ";"
comment_vim = false
comment_tab_width = 2
wrap = true
cursor_line = true
transparent_background = true
scroll_offset = 5
no_update_check = false
review_watch_interval_ms = 1000
